### ISSUE TITLE
Escaping &

### ISSUE THREAD

**Issue by alansmithnbs** [fiduswriter/xslt-processor#11]
This line - https://github.com/fiduswriter/xslt-processor/blob/a3a7c8386d7924dd16756a75ca6b2fe3a7ae4f77/src/util.js#L199

Means that if I have some XML with an `&amp;` in it, this will be replaced to `&amp;amp;`. I am fixing this by string replacing the output of the transform but it'd be great if I didn't have to do this. 

This is the only issue I've experienced, so please keep up the good work.

**Comment by johanneswilm** [comment]
@alansmithnbs thanks. patches are welcome!

**Comment by johanneswilm** [comment]
Actually, this is something I added because it did not work properly before. Could you write a test case where this is needed?

**Comment by johanneswilm** [comment]
Hey @alansmithnbs Could you be a bit more specific? I am looking at what characters need to be escaped in valid HTML/XML, and as far as I can tell, `&` is one of them [1]. If you can show me a case where this is not done correctly, please reopen this issue.

[1] https://stackoverflow.com/questions/1091945/what-characters-do-i-need-to-escape-in-xml-documents
