### ISSUE TITLE
node-set() function

### ISSUE THREAD

**Issue by Alessandro1990** [fiduswriter/xslt-processor#20]
Is there any implementation of the node-set function?

I'm able to convert an xml variable to node-set with the exsl extension, but i read that xslt-processor doesn't support extensions..

Below an example:
    
    <xsl:output method="xml" indent="yes" />
   
    <xsl:param name="x">
       <A>
          <B id="1"></B>
          <B id="2"></B>
       </A>
    </xsl:param>

    <xsl:param name="y" select="exsl:node-set($x)/A"/>

    <xsl:template match="/">
       <xsl:copy-of select="$y" />
    </xsl:template>

**Comment by johanneswilm** [comment]
Hey, could you use the repo search functionality and look for "node-set"? You will see it is mentioned a few times in the source code. If that is not enough for your needs, please add an entry in the TODO.
