### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by backslash47** [fiduswriter/xslt-processor#21]
Hello,

I see you changed the licence to LGPL v3.0 from the BSD 3-clause which the former **ajaxslt** project has. Do you have a strong reason for that? I am not a lawyer, but it will confuse people, because most of the code is still BSD licensed and only your changes are LGPL licensed. 

I myself have a rewrite to TypeScript + removed custom XPath and DOM implementation in favor of xpath-ts and xmldom/jsdom. I would rather licence it under one licence to not confuse people.

PS: have a loot at https://github.com/backslash47/xslt

**Comment by johanneswilm** [comment]
Yes, my reason is that I do free work and others should have to contribute back if they want to use it. All of the code is LGPL. I think you will likely only find white space that is the same as it was before my work started. 

Anyone is welcome to go back and use the decade old Google library. There is nothing confusing about that.

alternatively, if it is really important to have it be BSD 3 for some company, that company could try to pay me for the work I have done on this library and then have me revert it to BSD 3. But then they will also have to take over maintainership.

**Comment by johanneswilm** [comment]
@backslash47 I looked briefly at your TS version now.  As long as the license of it continues to be the LGPL, I would also agree to move development efforts there.

**Comment by backslash47** [comment]
Hi. Thank you for the clarification of your license choise. 

I don't have any problem with any reasonable open source licencie so let it be LGPL.

I am glad you look at the TS version.
I am currently integrating the library into a bigger application so I will most likely come with some bug fixes into the TS version as I might have made some bugs myself during the typing and externalizing xpath and dom implementation. And after the new year I will see what functionality is missing for my use case.

**Comment by johanneswilm** [comment]
Ok. If you want me to, I can set the status to "archived" and link to your version in the readme. This is assuming that it is set up to also compile to pure JS so that non-TS projects can use it out of npmjs.com.

I can also wait with that until you are done fixing all your issues first.
