### ISSUE TITLE
Feature request: distribute as transpiled output to support older browsers

### ISSUE THREAD

**Issue by karfau** [fiduswriter/xslt-processor#6]
As discussed in this [commit conversation](https://github.com/bettermarks/xslt-processor/commit/47447c0b2ad5006ef3e69888478eb781c80a4621#commitcomment-30963251) it would be nice to distribute the library in a transpiled way so it supports "older browsers".
The reason for our fork that moves default arguments methods into the methods was that we need to support chrome 48 which failed with a syntax error when loading this library.

Any hints for how to achieve this can be collected here, contributions seem to be welcome.

Anything to add @johanneswilm ?

Mentioning @saurabh2590 here that created the fork and commits.

**Comment by johanneswilm** [comment]
I would guess that the simplest would be to add a built target using the [rollup buble plugin](https://github.com/rollup/rollup-plugin-buble) to transpile to ES5.

**Comment by karfau** [comment]
I just checked that this issue has not been resolved from our perspective, since it's not working in Chrome 48:
```
Uncaught SyntaxError: Unexpected token =
```
@johanneswilm Can you please help me to understand, how to deal with this since you closed the ticket?
(our own fork is way behind this repo now and has security issues now, so we would prefer to switch back to the npm version.)
