### ISSUE TITLE
Using Jest might be better than bundeling jsunit

### ISSUE THREAD

**Issue by TheKnarf** [fiduswriter/xslt-processor#8]

**Comment by johanneswilm** [comment]
True. Jsunit survived from the pre-ES2015 version. You are welcome to make a PR replacing it with something more modern.

**Comment by johanneswilm** [comment]
@TheKnarf I have now replaced jsunit with jest everywhere. Thanks for the suggestion.

**Comment by TheKnarf** [comment]
Great job!
